include:
  - path: ./docker-compose.yml
    env_file: ./.env

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ragflow-ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - ollama-data:/root/.ollama
      - ../ollama-data/models:/root/.ollama/models
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 7869:11434
    networks:
      - ragflow

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: ollama-webui
    volumes:
      - ./ollama-data/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434/
      - ENABLE_SIGNUP=False
      - WEBUI_AUTH=False
      - WEBUI_NAME=Boring Jobs
      - WEBUI_URL=http://localhost:3000
      - WEBUI_SECRET_KEY=b0ring-j0bs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - ragflow

volumes:
  ollama-data:
    driver: local
